name: Build OS Images
on: workflow_dispatch


jobs:
  v3-hdmi-rpi4:
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: "${{secrets.DEPLOY_KEY}}"
      BOARD: rpi4
      PLATFORM: v3-hdmi
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configuring SSH
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H files.pikvm.org > ~/.ssh/known_hosts
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Creating config.mk
        run: |
          echo "BOARD=$BOARD" > config.mk
          echo "PLATFORM=$PLATFORM" >> config.mk
          echo "DEPLOY_USER=data" >> config.mk

      - name: Building OS
        run: make os NC=1

      - name: Making image
        run: make image

      - name: Uploading image
        run: make upload


  v2-hdmi-rpi4:
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: "${{secrets.DEPLOY_KEY}}"
      BOARD: rpi4
      PLATFORM: v2-hdmi
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configuring SSH
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H files.pikvm.org > ~/.ssh/known_hosts
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Creating config.mk
        run: |
          echo "BOARD=$BOARD" > config.mk
          echo "PLATFORM=$PLATFORM" >> config.mk
          echo "DEPLOY_USER=data" >> config.mk

      - name: Building OS
        run: make os NC=1

      - name: Making image
        run: make image

      - name: Uploading image
        run: make upload


  v2-hdmiusb-rpi4:
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: "${{secrets.DEPLOY_KEY}}"
      BOARD: rpi4
      PLATFORM: v2-hdmiusb
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configuring SSH
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H files.pikvm.org > ~/.ssh/known_hosts
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Creating config.mk
        run: |
          echo "BOARD=$BOARD" > config.mk
          echo "PLATFORM=$PLATFORM" >> config.mk
          echo "DEPLOY_USER=data" >> config.mk

      - name: Building OS
        run: make os NC=1

      - name: Making image
        run: make image

      - name: Uploading image
        run: make upload


  v2-hdmi-zerow:
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: "${{secrets.DEPLOY_KEY}}"
      BOARD: zerow
      PLATFORM: v2-hdmi
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configuring SSH
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H files.pikvm.org > ~/.ssh/known_hosts
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Creating config.mk
        run: |
          echo "BOARD=$BOARD" > config.mk
          echo "PLATFORM=$PLATFORM" >> config.mk
          echo "DEPLOY_USER=data" >> config.mk

      - name: Building OS
        run: make os NC=1

      - name: Making image
        run: make image

      - name: Uploading image
        run: make upload
