name: v1-hdmiusb-rpi2
on: workflow_dispatch


jobs:
  os:
    uses: pikvm/os/.github/workflows/os.yml@master
    with:
      BOARD: rpi2
      PLATFORM: v1-hdmiusb
    secrets:
      DEPLOY_KEY: "${{secrets.DEPLOY_KEY}}"
